(setq auto-mode-alist (cons '("\\.hql$" . sql-mode) auto-mode-alist))
(setq auto-mode-alist (cons '("\\.scala$" . ruby-mode) auto-mode-alist))
(setq auto-mode-alist (cons '("\\.ts$" . js-mode) auto-mode-alist))
(setq auto-mode-alist (cons '("\\.tsx$" . js-mode) auto-mode-alist))
(setq auto-mode-alist (cons '("\\.tf$" . hcl-mode) auto-mode-alist))
